#!/usr/bin/env bun

import { createHash } from "node:crypto";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { resolveBuildRuntimeSources } from "@thinkrail/server/build-support";
import { binaryArtifactName } from "./artifactName";

const cliDir = resolve(import.meta.dir, "..");
const repoRoot = resolve(cliDir, "..", "..");
const webDist = join(repoRoot, "apps", "web", "dist");
const webGeneratedPath = join(cliDir, "src", "web-assets.generated.ts");
const extGeneratedPath = join(cliDir, "src", "bundled-extensions.generated.ts");
const runtimeGeneratedPath = join(cliDir, "src", "runtime-assets.generated.ts");
const entryPath = join(cliDir, "src", "compiled-entry.ts");
const outDir = join(cliDir, "dist");
const runtimeSources = resolveBuildRuntimeSources();

function listFiles(dir: string): string[] {
	const out: string[] = [];
	for (const name of readdirSync(dir)) {
		const full = join(dir, name);
		if (statSync(full).isDirectory()) out.push(...listFiles(full));
		else out.push(full);
	}
	return out;
}

function embedFiles(
	files: { root: string; file: string }[],
	importPrefix: string,
): { imports: string[]; entries: string[]; version: string } {
	const hash = createHash("sha256");
	const imports: string[] = [];
	const entries: string[] = [];
	const seen = new Set<string>();
	files.forEach(({ root, file }, i) => {
		const route = relative(root, file).split(sep).join("/");
		if (seen.has(route)) throw new Error(`duplicate embedded route: ${route}`);
		seen.add(route);
		hash.update(route).update(readFileSync(file));
		imports.push(`import ${importPrefix}${i} from ${JSON.stringify(file)} with { type: "file" };`);
		entries.push(`\t{ route: ${JSON.stringify(route)}, data: ${importPrefix}${i} },`);
	});
	return { imports, entries, version: hash.digest("hex").slice(0, 16) };
}

function generateWebManifest(): void {
	if (!existsSync(join(webDist, "index.html"))) {
		throw new Error(`web build not found at ${webDist} — run \`bun run build:web\` first.`);
	}
	const files = listFiles(webDist)
		.sort()
		.map((file) => ({ root: webDist, file }));
	const { imports, entries, version } = embedFiles(files, "a");
	writeFileSync(
		webGeneratedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Embeds apps/web/dist into the single-file binary.\n${imports.join("\n")}\n\nexport const webAssetsVersion = ${JSON.stringify(version)};\nexport const embeddedWebAssets = [\n${entries.join("\n")}\n];\n`,
	);
}

function generateBundledExtensions(): void {
	const entryPaths = runtimeSources.extensions.map((extension) => extension.entry);
	const factoryImports = entryPaths.map((path, i) => `import x${i} from ${JSON.stringify(path)};`);
	const skillRoots = runtimeSources.extensions.flatMap((extension) =>
		extension.skills ? [extension.skills] : [],
	);
	const skillFiles = skillRoots.flatMap((root) =>
		listFiles(root)
			.sort()
			.map((file) => ({ root, file })),
	);
	const { imports, entries, version } = embedFiles(skillFiles, "s");
	writeFileSync(
		extGeneratedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Value-imports the bundled pi extensions and\n// embeds their skills into the single-file binary.\n${factoryImports.join("\n")}\n${imports.join("\n")}\n\nexport const bundledExtensionFactories = [x0, x1, x2, x3, x4];\nexport const bundledWebAccessFactory = x0;\nexport const bundledSkillsVersion = ${JSON.stringify(version)};\nexport const embeddedSkillFiles = [\n${entries.join("\n")}\n];\n`,
	);
}

function generateRuntimeManifest(): void {
	const files = [runtimeSources.trashHelpers.macos, runtimeSources.trashHelpers.windows].map(
		(file) => ({ root: dirname(file), file }),
	);
	const { imports, entries, version } = embedFiles(files, "r");
	writeFileSync(
		runtimeGeneratedPath,
		`// GENERATED by scripts/build-binary.ts — do not edit. Embeds native runtime helper sidecars.\n${imports.join("\n")}\n\nexport const runtimeAssetsVersion = ${JSON.stringify(version)};\nexport const embeddedRuntimeAssets = [\n${entries.join("\n")}\n];\n`,
	);
}

const target = process.argv.find((a) => a.startsWith("--target="))?.slice("--target=".length);
const outFile = join(outDir, binaryArtifactName(target));

mkdirSync(outDir, { recursive: true });
generateWebManifest();
generateBundledExtensions();
generateRuntimeManifest();
try {
	const proc = Bun.spawnSync(
		[
			"bun",
			"build",
			"--compile",
			"--no-compile-autoload-bunfig",
			"--bytecode",
			"--format=esm",
			`--target=${target ?? "bun"}`,
			entryPath,
			"--outfile",
			outFile,
		],
		{ stdout: "inherit", stderr: "inherit", cwd: cliDir },
	);
	if (!proc.success) process.exit(proc.exitCode ?? 1);
} finally {
	rmSync(webGeneratedPath, { force: true });
	rmSync(extGeneratedPath, { force: true });
	rmSync(runtimeGeneratedPath, { force: true });
}
console.log(`\nBuilt single-file binary: ${outFile}`);
